name: s2geometry
description: Dart port of the S2 Geometry library
version: 1.0.0
homepage: https://github.com/nbspou/dart-s2geometry
author: Jan Boon <kaetemi@no-break.space>

environment:
  sdk: '>=3.4.3 <4.0.0'
  

dependencies:
  test: any
  protobuf: ^2.0.0

dev_dependencies:
  
